/* Generated By:JavaCC: Do not edit this line. ArbolTreeConstants.java Version 5.0 */
package Aritmetica;

public interface ArbolTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTATEMENT = 1;
  public int JJTEMBEDDED_STATEMENT = 2;
  public int JJTEXPRESSION_STATEMENT = 3;
  public int JJTSTATEMENT_EXPRESSION = 4;
  public int JJTDECLARATION_STATEMENT = 5;
  public int JJTLOCAL_VARIABLE_DECLARATION = 6;
  public int JJTLOCAL_VARIABLE_TYPE = 7;
  public int JJTTYPE = 8;
  public int JJTVALUE_TYPE = 9;
  public int JJTNON_NULLABLE_VALUE_TYPE = 10;
  public int JJTSTRUCT_TYPE = 11;
  public int JJTSIMPLE_TYPE = 12;
  public int JJTNUMERIC_TYPE = 13;
  public int JJTINTEGRAL_TYPE = 14;
  public int JJTFLOATING_POINT_TYPE = 15;
  public int JJTLOCAL_VARIABLE_DECLARATORS = 16;
  public int JJTLOCAL_VARIABLE_DECLARATOR = 17;
  public int JJTLOCAL_VARIABLE_INITIALIZER = 18;
  public int JJTEXPRESSION = 19;
  public int JJTASSIGNMENT = 20;
  public int JJTNON_ASSIGNMENT_EXPRESSION = 21;
  public int JJTCONDITIONAL_EXPRESSION = 22;
  public int JJTNULL_COALESCING_EXPRESSION = 23;
  public int JJTCONDITIONAL_OR_EXPRESSION = 24;
  public int JJTCONDITIONAL_AND_EXPRESSION = 25;
  public int JJTINCLUSIVE_OR_EXPRESSION = 26;
  public int JJTEXCLUSIVE_OR_EXPRESSION = 27;
  public int JJTAND_EXPRESSION = 28;
  public int JJTEQUALITY_EXPRESSION = 29;
  public int JJTRELATIONAL_EXPRESSION = 30;
  public int JJTSHIFT_EXPRESSION = 31;
  public int JJTADDITIVE_EXPRESSION = 32;
  public int JJTMULTIPLICATIVE_EXPRESSION = 33;
  public int JJTUNARY_EXPRESSION = 34;
  public int JJTPRE_INCREMENT_EXPRESSION = 35;
  public int JJTPRE_DECREMENT_EXPRESSION = 36;
  public int JJTPRIMARY_EXPRESSION = 37;
  public int JJTPRIMARY_NO_ARRAY_CREATION_EXPRESSION = 38;
  public int JJTPOST_DECREMENT_EXPRESSION = 39;
  public int JJTPOST_INCREMENT_EXPRESSION = 40;
  public int JJTLITERAL = 41;
  public int JJTSIMPLE_NAME = 42;
  public int JJTPARENTHESIZED_EXPRESSION = 43;


  public String[] jjtNodeName = {
    "Start",
    "statement",
    "embedded_statement",
    "expression_statement",
    "statement_expression",
    "declaration_statement",
    "local_variable_declaration",
    "local_variable_type",
    "type",
    "value_type",
    "non_nullable_value_type",
    "struct_type",
    "simple_type",
    "numeric_type",
    "integral_type",
    "floating_point_type",
    "local_variable_declarators",
    "local_variable_declarator",
    "local_variable_initializer",
    "expression",
    "assignment",
    "non_assignment_expression",
    "conditional_expression",
    "null_coalescing_expression",
    "conditional_or_expression",
    "conditional_and_expression",
    "inclusive_or_expression",
    "exclusive_or_expression",
    "and_expression",
    "equality_expression",
    "relational_expression",
    "shift_expression",
    "additive_expression",
    "multiplicative_expression",
    "unary_expression",
    "pre_increment_expression",
    "pre_decrement_expression",
    "primary_expression",
    "primary_no_array_creation_expression",
    "post_decrement_expression",
    "post_increment_expression",
    "literal",
    "simple_name",
    "parenthesized_expression",
  };
}
/* JavaCC - OriginalChecksum=e15083dda3aa3c1b527c0363f8c75acd (do not edit this line) */
